#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
#
# Purpose: provision the one-time fly.io credential the CI deploy job
# (.github/workflows/ci.yml, `deploy` job) needs — a deploy-scoped token stored
# as the FLY_API_TOKEN repository secret — plus the recommended branch
# protection on `main`. CI cannot do any of this itself.
#
# The token is deliberately NEVER captured, printed, or written to a file by
# this wizard: `fly` shows it once, you copy it, and `gh secret set` (or the
# GitHub dashboard) takes it straight from your paste. Re-running the wizard is
# safe — every stage is idempotent or a no-op.

TOTAL_STAGES=5

# Resolve owner/repo for the GitHub URLs — prefer gh, fall back to the remote.
REPO=""
if command -v gh >/dev/null 2>&1 && gh repo view --json nameWithOwner -q .nameWithOwner >/dev/null 2>&1; then
  REPO=$(gh repo view --json nameWithOwner -q .nameWithOwner)
elif git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  REPO=$(git remote get-url origin 2>/dev/null | sed -E 's#(git@github.com:|https://github.com/)##; s#\.git$##')
fi
REPO="${REPO:-UberJoe/fpldiscord}"

FLY_HEALTH_URL="https://fpldiscord.fly.dev/healthz"

banner "Fly deploy token → CI"

# ── Stage 1 — flyctl is installed and pointed at the right account ────────
stage "Fly CLI — confirm the right account"
say "The deploy token is scoped to whatever account 'fly' is logged in as."
if ! command -v flyctl >/dev/null 2>&1 && ! command -v fly >/dev/null 2>&1; then
  warn "flyctl is not installed."
  open_url "https://fly.io/docs/flyctl/install/"
  say "Install it, restart this shell, then re-run the wizard."
  exit 1
fi
FLY=$(command -v flyctl || command -v fly)
step "Check who you are:  $FLY auth whoami"
"$FLY" auth whoami || {
  warn "Not logged in."
  say "Run '$FLY auth login' in another terminal, then come back."
  pause "Logged in now?"
  "$FLY" auth whoami
}
confirm "Is that the account that owns the 'fpldiscord' app?" || {
  say "Run '$FLY auth login' as the correct account, then re-run this wizard."
  exit 1
}

# ── Stage 2 — mint a deploy-scoped token ─────────────────────────────────
stage "Mint the deploy token"
say "A DEPLOY-scoped token can push releases and nothing else — it is not an"
say "org token and not a personal access token. One-year expiry (8760h)."
warn "fly prints the token value exactly once. Copy the whole 'FlyV1 …' string"
warn "the moment it appears — including the 'FlyV1 ' prefix and any trailing =."
pause "Ready to mint it?"
step "Running:  $FLY tokens create deploy -x 8760h -n \"github-actions-deploy\""
printf '\n'
"$FLY" tokens create deploy -x 8760h -n "github-actions-deploy"
printf '\n'
say "Select and copy the FlyV1 token above now."
pause "Copied?"

# ── Stage 3 — store it as the FLY_API_TOKEN repo secret ──────────────────
stage "Store it as the FLY_API_TOKEN repo secret"
say "CI reads this secret as \${{ secrets.FLY_API_TOKEN }} in the deploy job."
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  say "gh is ready — it will prompt for the value with hidden input. This wizard"
  say "never sees or stores the token; it goes straight from your paste to GitHub."
  pause "Press Enter, then paste the token at gh's prompt."
  if gh secret set FLY_API_TOKEN --repo "$REPO"; then
    WRITTEN_SECRET+=("FLY_API_TOKEN")
    printf '  %s✓ set%s GitHub secret FLY_API_TOKEN on %s\n' "$GREEN" "$RESET" "$REPO"
  else
    warn "gh secret set failed — use the dashboard instead (steps below)."
    SKIPPED+=("FLY_API_TOKEN repo secret — add via the dashboard")
    open_url "https://github.com/$REPO/settings/secrets/actions/new"
    step "Name: FLY_API_TOKEN"
    step "Secret: paste the FlyV1 value"
    step "Add secret"
    pause "Added?"
  fi
else
  note "gh not installed / not authenticated — using the dashboard."
  open_url "https://github.com/$REPO/settings/secrets/actions/new"
  step "New repository secret"
  step "Name: FLY_API_TOKEN  (exactly — CI matches on this)"
  step "Secret: paste the whole FlyV1 value"
  step "Click 'Add secret'"
  SKIPPED+=("FLY_API_TOKEN repo secret — confirm it saved on $REPO")
  pause "Added?"
fi

# ── Stage 4 — recommended: require the test check on main ────────────────
stage "Recommended — branch protection on main"
say "So a red 'test' check blocks merge. This is a recommendation; no ticket"
say "applies it for you."
open_url "https://github.com/$REPO/settings/branches"
step "Add branch protection rule (or a ruleset) for branch name pattern: main"
step "Enable 'Require status checks to pass before merging'"
step "Search the status-check list for 'test' and select it"
step "Save changes"
note "The 'test' check only appears in that list after the workflow has run"
note "at least once — open a PR first if you don't see it yet."
pause "Done (or noted for later)?"

# ── Stage 5 — verify CI can authenticate ────────────────────────────────
stage "Verify the deploy job authenticates"
say "The deploy job runs only on a push to main. Trigger one and watch it."
step "Push a trivial commit to main, or re-run the latest 'CI' run from the"
step "Actions tab (Re-run all jobs)."
open_url "https://github.com/$REPO/actions"
say "On that run, confirm:"
step "the 'deploy' job starts (it needs the 'test' job green first)"
step "'flyctl deploy --remote-only' authenticates — no 'Error: No access token'"
step "the post-deploy step polls $FLY_HEALTH_URL and gets 200"
note "No 'deploy' job yet? It ships with ticket 05 (same ci.yml). Provisioning"
note "the token now unblocks that job's first green run."
confirm "Did the deploy job authenticate and the health poll pass?" \
  && say "Pipeline is proven end to end." \
  || SKIPPED+=("Re-check the deploy job once ticket 05's job is on main")

finish
